apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "loggers.okofs.com"
webhooks:
  - name: "loggers.okofs.com"
    rules:
    - apiGroups: ["okofs.com"]
      apiVersions: ["v1alpha1"]
      operations: ["CREATE"]
      resources: ["loggers"]
      scope: "Namespaced"
    clientConfig:
      service:
        namespace: "default"
        name: "validating-kontroller"
      caBundle: ""
    admissionReviewVersions: ["v1", "v1alpha1"]
    sideEffects: None
    timeoutSeconds: 5
